# General Site Settings
# =============================
# This is where you can change any text in the website. From titles to description, from services and featured
# gallery video.
#
# Parts of the website has pretty straightforward names but for more complex changes, you may need some knowledge
# on basic CSS and HTML.
#
# To look for keywords press CTRL + F (Windows) / CMD + F (Mac) and type the text you want to find.
# A table of contents has been laid out for your convenience.
#
# Table of Contents:
# 1) Navigation
# 2) About
# 3) Services
# 4) Gallery

# =============================
# Navigation

# READ ME: To add more links, simply add a new line by copy pasting! Only change what is in between quotes!
#          if in some cases you wanted to change links (url), do it at your own risk!
#

nav:
- {name: "Welcome", url: '#welcome'}
- {name: "About", url: '#about'}
- {name: "Services", url: '#services'}
- {name: "Gallery", url: '#gallery'}
- {name: "Team", url: '#'}
- {name: "Packages", url: '#'}
- {name: "Contacts", url: '#'}

# =============================
# About
#
# To break into a new line. Input 1 <br/>, to break into a new paragraph. Input 2 <br/>

about-title: "Welcome to In Style Events"

# READ ME: <br> - breaks a line into two lines.

about-description: "From intimate executive forums to large scale events like corporate events, weddings, debuts and everything in between,
In Style Events can help you to successfully achieve your objectives within the perimeters of your budget.<br/>
<br/>
Wedding is the most special and memorable day in one's life. That's why In Style Events Team  will give every single
effort to make that moment extra ordinary and make your dream wedding a reality.<br/>
<br/>
We understand that every couple has unique taste and desire. Therefore, we offer services according to the clients
need. Its ideal for all the client who needs assistance from planning, initiation, down to the preparation and utmost
end of the event."

# =============================
# Services
#
# Some knowledge is needed in order to change the icons, do it at your own risk!
#
# Icons have been taken from www.fontawesome.com and is free for public use.

services-title: "Our Services"
services-subtitle: "From event planners & coordinators to hosts. <br/> We make sure to deliver customer satisfaction through our services."

services:
- {name: "Event Planners & Coordinators", icon: "fa-users"}
- {name: "Photo & Video Services", icon: "fa-camera-retro"}
- {name: "Lights & Sound System", icon: "fa-lightbulb-o"}
- {name: "Personalized Wedding Cords & Candles", icon: "fa-magic"}
- {name: "Florist & Event Stylist", icon: "fa-paint-brush"}
- {name: "Bridal Car & Van Rentals", icon: "fa-car"}
- {name: "Host", icon: "fa-user"}

# =============================
# Services
#
# To change the embedded featured video. You need to grab the video's ID in youtube.
# Please note that the featured video works only for youtube. For wistia you may need to
# edit the source code directly.
#
# You may find the source code at "_includes/gallery.html" line 13
#
# Example on how to change featured video (youtube)
#
#   https://www.youtube.com/watch?v=dQw4w9WgXcQ
#   - the letters after v= is what you need. (dQw4w9WgXcQ)
#
#   Final result will be:
#   gallery-featured-video: "dQw4w9WgXcQ"

gallery-title: "Our Gallery"
gallery-subtitle: "Our most recent gallery updates. These are just the tip of the iceberg...<br>
  Make sure to check all our work by visiting our full gallery page."

gallery-featured-video: "3xAK8dzffn8"
