# =============================
# Landing Page Settings (main-text)

# READ ME: This is the main text of the landing page.
# IMPORTANT: You can add more slides to the landing page by opening slider.yml file.

slider-text: "Welcome to <strong>Instyle Events!</strong>"

# =============================
# Landing Page Settings (tagline)

# READ ME: Before you change the tagline in the welcome page, some notes to remember:
#          <br> - breaks a line into two lines.
#          e.g  - Makes every moment Memorable... (when added <br> it turns into)
#                         -
#                 Makes every moment
#                     Memorable...
#          <span> - changes the text color to #FF0030 or Red.
#
# Remember: Avoid having too long taglines! It's best to keep it under 8 words to not break the layout.

slider-tagline: "Makes every moment <span>Memorable</span>..."

# =============================
# Landing Page Settings (background)

# READ ME: Here you can change the first slide's background. I recommend to use a 1080x780 size for backgrounds,
#          so it will not take too much time to load!

slider-background: "slide-1.jpg"

# =============================
# Navigation

# READ ME: To add more links, simply add a new line by copy pasting! Only change what is in between quotes!
#          if in some cases you wanted to change links (url), do it at your own risk!

nav:
- {name: "Welcome", url: '#welcome'}
- {name: "About", url: '#about'}
- {name: "Services", url: '#services'}
- {name: "Gallery", url: '#'}
- {name: "Team", url: '#'}
- {name: "Packages", url: '#'}
- {name: "Contacts", url: '#'}

# =============================
# About

about-title: "Welcome to In Style Events"

# READ ME: <br> - breaks a line into two lines.

about-description: "From intimate executive forums to large scale events like corporate events, weddings, debuts and everything in between,
In Style Events can help you to successfully achieve your objectives within the perimeters of your budget.<br/>
<br/>
Wedding is the most special and memorable day in one's life. That's why In Style Events Team  will give every single
effort to make that moment extra ordinary and make your dream wedding a reality.<br/>
<br/>
We understand that every couple has unique taste and desire. Therefore, we offer services according to the clients
need. Its ideal for all the client who needs assistance from planning, initiation, down to the preparation and utmost
end of the event."

# =============================
# Services

services-title: "Our Services"
services-subtitle: "From event planners & coordinators to hosts. <br/> We make sure to deliver customer satisfaction through our services."

services:
- {name: "Event Planners & Coordinators", icon: "fa-users"}
- {name: "Photo & Video Services", icon: "fa-camera-retro"}
- {name: "Lights & Sound System", icon: "fa-lightbulb-o"}
- {name: "Personalized Wedding Cords & Candles", icon: "fa-magic"}
- {name: "Florist & Event Stylist", icon: "fa-paint-brush"}
- {name: "Bridal Car & Van Rentals", icon: "fa-car"}
- {name: "Host", icon: "fa-user"}
